name: Build LaTeX document
on:
  push:
    branches:
      - main

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Make pdf directory
        run: |
          mkdir pdf
          cd pdf
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: ../resume.tex
      - name: Deploy to gh pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./pdf
