name: Build LaTeX document
on:
  push:
    branches:
      - main
permissions:
  contents: write

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: resume.tex
          post_compile: "mkdir pdfs; mv resume.pdf pdfs/resume.pdf; "
      - name: Deploy to gh pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./pdfs
